<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.5">
  <POU Name="MAIN" Id="{d1e7ffc5-0e5e-40b6-83db-d6d43156a01c}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM INTERNAL MAIN
VAR
	_driveTest : fbDriveTest;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>